version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_PORT_3306_TCP_ADDR: db




